import { defaultConfig } from "./constants";

/**
 *
 * Utility function to check if the user config is same as default.
 *
 * @param	{Object[]} initConfig 	- config generated by the user.
 * @returns {Boolean} - Whether the default config is used or not.
 */

export default function checkDefaults(property: string, value: any): boolean {
	console.log({ property, value });
	return defaultConfig[property] === value;
}
